server:
  port: 8090
  host: 0.0.0.0

alpha:
  server:
    host: ${server.host}
    port: 8080
  feature:
    nativetransport: false # Default disabled Netty Native Transport



spring:
  profiles:
    active: prd
  datasource:
    initialization-mode: NEVER #always
  main:
    allow-bean-definition-overriding: true
#  cloud:
#    consul:
#      host: 0.0.0.0
#      port: 8500
#      discovery:
#        serviceName: {spring.application.name}
#        healthCheckPath: /actuator/health
#        healthCheckInterval: 10s
#        instanceId: ${spring.application.name}-${alpha.server.host}-${random.value}
#        tags: saga-server-host=${alpha.server.host},saga-server-port=${alpha.server.port}

eureka:
  client:
    enabled: false
  instance:
    metadataMap:
      saga-server: ${alpha.server.host}:${alpha.server.port}



#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
#  health:
#    redis:
#      enabled: false
#    elasticsearch:
#      enabled: false

---
spring:
  profiles: ssl
alpha:
  server:
    ssl:
      enable: true
      cert: server.crt
      key: server.pem
      mutualAuth: true
      clientCert: client.crt
        
---
spring:
  profiles: prd
  datasource:
    username: saga
    password: password
    url: jdbc:postgresql://postgresql.servicecomb.io:5432/saga_dev?useSSL=false
    platform: postgresql
    continue-on-error: false
#    driver-class-name: org.postgresql.Driver

  jpa:
#    open-in-view: false
    properties:
      eclipselink:
        ddl-generation: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

---
spring:
  profiles: mysql
  datasource:
    username: saga
    password: password
    url: jdbc:mysql://mysql.servicecomb.io:3306/saga?useSSL=false
    platform: mysql
    continue-on-error: false
  jpa:
    properties:
      eclipselink:
        ddl-generation: none
